/*
 * similarProductEngineAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.inditex.zarachallenge.infrastructure.rest.similarProductEngineAPI.client;

import java.util.Set;
import org.junit.Test;
import org.junit.Ignore;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for DefaultClientApi
 */
@Ignore
public class DefaultClientApiTest {

    private final DefaultClientApi api = new DefaultClientApi();

    
    /**
     * Gets the ids of the similar products
     *
     * Returns the similar products to a given one ordered by similarity
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getProductSimilaridsTest() {
        String productId = null;

        Set<String> response = api.getProductSimilarids(productId);

        // TODO: test validations
    }
    
}
